package lk.janith.tuitionmanagement.service;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.draw.LineSeparator;
import lk.janith.tuitionmanagement.entity.Payment;
import lk.janith.tuitionmanagement.enums.PaymentStatus;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;

@Service
public class PaymentReceiptPdfService {

    private static final Color PRIMARY = new Color(37, 99, 235);
    private static final Color DARK = new Color(15, 23, 42);
    private static final Color MUTED = new Color(100, 116, 139);
    private static final Color BORDER = new Color(226, 232, 240);
    private static final Color LIGHT_BG = new Color(248, 250, 252);

    private static final Color SUCCESS = new Color(22, 163, 74);
    private static final Color WARNING = new Color(217, 119, 6);
    private static final Color DANGER = new Color(220, 38, 38);

    public void generateReceipt(Payment payment, OutputStream outputStream) {
        try {
            Document document = new Document(PageSize.A4, 36, 36, 34, 34);
            PdfWriter.getInstance(document, outputStream);

            document.open();

            addHeader(document);
            addStatusSeal(document, payment);
            addReceiptMeta(document, payment);
            addStudentAndBatchDetails(document, payment);
            addPaymentDetails(document, payment);
            addFooter(document);

            document.close();

        } catch (Exception e) {
            throw new RuntimeException("Could not generate payment receipt", e);
        }
    }

    private void addHeader(Document document) throws Exception {
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{1.2f, 3.8f});
        headerTable.setSpacingAfter(18);

        // Left badge instead of logo
        PdfPCell badgeCell = new PdfPCell();
        badgeCell.setBorder(Rectangle.NO_BORDER);
        badgeCell.setVerticalAlignment(Element.ALIGN_MIDDLE);

        PdfPTable badgeTable = new PdfPTable(1);
        badgeTable.setWidthPercentage(72);

        PdfPCell badge = new PdfPCell();
        badge.setBackgroundColor(PRIMARY);
        badge.setBorder(Rectangle.NO_BORDER);
        badge.setPaddingTop(18);
        badge.setPaddingBottom(18);
        badge.setHorizontalAlignment(Element.ALIGN_CENTER);

        Paragraph badgeText = new Paragraph(
                "ET",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 26, Color.WHITE)
        );
        badgeText.setAlignment(Element.ALIGN_CENTER);

        Paragraph badgeSmallText = new Paragraph(
                "Receipt",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, Color.WHITE)
        );
        badgeSmallText.setAlignment(Element.ALIGN_CENTER);

        badge.addElement(badgeText);
        badge.addElement(badgeSmallText);

        badgeTable.addCell(badge);
        badgeCell.addElement(badgeTable);

        headerTable.addCell(badgeCell);

        // Right title section
        PdfPCell titleCell = new PdfPCell();
        titleCell.setBorder(Rectangle.NO_BORDER);
        titleCell.setVerticalAlignment(Element.ALIGN_MIDDLE);

        Paragraph academyName = new Paragraph(
                "EduTrack Tuition Management",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, DARK)
        );
        academyName.setAlignment(Element.ALIGN_RIGHT);

        Paragraph subtitle = new Paragraph(
                "Student Payment Receipt",
                FontFactory.getFont(FontFactory.HELVETICA, 11, MUTED)
        );
        subtitle.setAlignment(Element.ALIGN_RIGHT);

        Paragraph contact = new Paragraph(
                "Generated by Tuition Class Student Management System",
                FontFactory.getFont(FontFactory.HELVETICA, 9, MUTED)
        );
        contact.setAlignment(Element.ALIGN_RIGHT);

        titleCell.addElement(academyName);
        titleCell.addElement(subtitle);
        titleCell.addElement(contact);

        headerTable.addCell(titleCell);

        document.add(headerTable);

        LineSeparator line = new LineSeparator();
        line.setLineColor(BORDER);
        document.add(line);
    }

    private void addStatusSeal(Document document, Payment payment) throws Exception {
        String statusText = getStatusText(payment.getStatus());
        Color sealColor = getStatusColor(payment.getStatus());

        PdfPTable sealTable = new PdfPTable(1);
        sealTable.setWidthPercentage(100);
        sealTable.setSpacingBefore(16);
        sealTable.setSpacingAfter(16);

        PdfPCell sealCell = new PdfPCell();
        sealCell.setBorder(Rectangle.NO_BORDER);
        sealCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        sealCell.setPadding(0);

        Paragraph seal = new Paragraph(
                statusText,
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.WHITE)
        );
        seal.setAlignment(Element.ALIGN_CENTER);

        PdfPCell innerSeal = new PdfPCell(seal);
        innerSeal.setBackgroundColor(sealColor);
        innerSeal.setBorder(Rectangle.NO_BORDER);
        innerSeal.setPaddingTop(12);
        innerSeal.setPaddingBottom(12);
        innerSeal.setHorizontalAlignment(Element.ALIGN_CENTER);

        PdfPTable innerTable = new PdfPTable(1);
        innerTable.setWidthPercentage(42);
        innerTable.addCell(innerSeal);

        sealCell.addElement(innerTable);
        sealTable.addCell(sealCell);

        document.add(sealTable);
    }

    private void addReceiptMeta(Document document, Payment payment) throws Exception {
        PdfPTable metaTable = new PdfPTable(2);
        metaTable.setWidthPercentage(100);
        metaTable.setWidths(new float[]{1, 1});
        metaTable.setSpacingAfter(14);

        PdfPCell receiptNo = createInfoBox(
                "Receipt No",
                "REC-" + String.format("%05d", payment.getId())
        );

        PdfPCell paymentDate = createInfoBox(
                "Payment Date",
                payment.getPaymentDate() != null
                        ? payment.getPaymentDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
                        : "-"
        );

        receiptNo.setPaddingRight(6);
        paymentDate.setPaddingLeft(6);

        metaTable.addCell(receiptNo);
        metaTable.addCell(paymentDate);

        document.add(metaTable);
    }

    private void addStudentAndBatchDetails(Document document, Payment payment) throws Exception {
        PdfPTable mainTable = new PdfPTable(2);
        mainTable.setWidthPercentage(100);
        mainTable.setWidths(new float[]{1, 1});
        mainTable.setSpacingAfter(16);

        PdfPTable studentTable = createSectionTable("Student Details");
        addRow(studentTable, "Student Code", safe(payment.getEnrollment().getStudent().getStudentCode()));
        addRow(studentTable, "Student Name", safe(payment.getEnrollment().getStudent().getFullName()));
        addRow(studentTable, "Phone", safe(payment.getEnrollment().getStudent().getPhone()));
        addRow(studentTable, "Grade", safe(payment.getEnrollment().getStudent().getGrade()));

        PdfPTable batchTable = createSectionTable("Batch Details");
        addRow(batchTable, "Batch", safe(payment.getEnrollment().getBatch().getBatchName()));
        addRow(batchTable, "Subject", safe(payment.getEnrollment().getBatch().getSubject()));
        addRow(batchTable, "Teacher", safe(payment.getEnrollment().getBatch().getTeacherName()));
        addRow(batchTable, "Monthly Fee", formatMoney(payment.getEnrollment().getBatch().getMonthlyFee()));

        PdfPCell studentCell = new PdfPCell(studentTable);
        studentCell.setBorder(Rectangle.NO_BORDER);
        studentCell.setPaddingRight(8);

        PdfPCell batchCell = new PdfPCell(batchTable);
        batchCell.setBorder(Rectangle.NO_BORDER);
        batchCell.setPaddingLeft(8);

        mainTable.addCell(studentCell);
        mainTable.addCell(batchCell);

        document.add(mainTable);
    }

    private void addPaymentDetails(Document document, Payment payment) throws Exception {
        PdfPTable paymentTable = createSectionTable("Payment Details");
        paymentTable.setSpacingAfter(20);

        addRow(paymentTable, "Payment Month", getMonthName(payment.getPaymentMonth()) + " " + payment.getPaymentYear());
        addRow(paymentTable, "Expected Amount", formatMoney(payment.getExpectedAmount()));
        addRow(paymentTable, "Paid Amount", formatMoney(payment.getPaidAmount()));
        addRow(paymentTable, "Balance Amount", formatMoney(payment.getBalanceAmount()));
        addRow(paymentTable, "Payment Method", safe(payment.getPaymentMethod()));
        addRow(paymentTable, "Status", getStatusText(payment.getStatus()));
        addRow(paymentTable, "Remarks", payment.getRemarks() == null || payment.getRemarks().isBlank() ? "-" : payment.getRemarks());

        document.add(paymentTable);
    }

    private void addFooter(Document document) throws Exception {
        PdfPTable footerTable = new PdfPTable(2);
        footerTable.setWidthPercentage(100);
        footerTable.setWidths(new float[]{1, 1});
        footerTable.setSpacingBefore(22);

        PdfPCell noteCell = new PdfPCell();
        noteCell.setBorder(Rectangle.NO_BORDER);

        Paragraph noteTitle = new Paragraph(
                "Note",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, DARK)
        );

        Paragraph note = new Paragraph(
                "This is a computer-generated receipt. Please keep this receipt for future reference.",
                FontFactory.getFont(FontFactory.HELVETICA, 9, MUTED)
        );

        noteCell.addElement(noteTitle);
        noteCell.addElement(note);

        PdfPCell signatureCell = new PdfPCell();
        signatureCell.setBorder(Rectangle.NO_BORDER);
        signatureCell.setHorizontalAlignment(Element.ALIGN_RIGHT);

        Paragraph line = new Paragraph(
                "________________________",
                FontFactory.getFont(FontFactory.HELVETICA, 10, DARK)
        );
        line.setAlignment(Element.ALIGN_RIGHT);

        Paragraph signature = new Paragraph(
                "Authorized Signature",
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, MUTED)
        );
        signature.setAlignment(Element.ALIGN_RIGHT);

        signatureCell.addElement(line);
        signatureCell.addElement(signature);

        footerTable.addCell(noteCell);
        footerTable.addCell(signatureCell);

        document.add(footerTable);
    }

    private PdfPCell createInfoBox(String label, String value) {
        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(LIGHT_BG);
        cell.setBorderColor(BORDER);
        cell.setPadding(12);

        Paragraph labelText = new Paragraph(
                label,
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, MUTED)
        );

        Paragraph valueText = new Paragraph(
                value,
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13, DARK)
        );

        cell.addElement(labelText);
        cell.addElement(valueText);

        return cell;
    }

    private PdfPTable createSectionTable(String title) throws Exception {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1.25f, 2.75f});
        table.setSpacingBefore(4);

        PdfPCell titleCell = new PdfPCell(
                new Phrase(title, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.WHITE))
        );
        titleCell.setColspan(2);
        titleCell.setBackgroundColor(PRIMARY);
        titleCell.setBorder(Rectangle.NO_BORDER);
        titleCell.setPadding(10);

        table.addCell(titleCell);

        return table;
    }

    private void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(
                new Phrase(label, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, MUTED))
        );
        labelCell.setBackgroundColor(LIGHT_BG);
        labelCell.setBorderColor(BORDER);
        labelCell.setPadding(9);

        PdfPCell valueCell = new PdfPCell(
                new Phrase(value, FontFactory.getFont(FontFactory.HELVETICA, 9, DARK))
        );
        valueCell.setBorderColor(BORDER);
        valueCell.setPadding(9);

        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private String formatMoney(BigDecimal amount) {
        if (amount == null) {
            return "LKR 0.00";
        }

        return "LKR " + amount.setScale(2).toPlainString();
    }

    private String safe(Object value) {
        return value == null ? "-" : String.valueOf(value);
    }

    private String getStatusText(PaymentStatus status) {
        if (status == null) {
            return "UNKNOWN";
        }

        return switch (status) {
            case PAID -> "PAID";
            case PARTIAL -> "PARTIALLY PAID";
            case UNPAID -> "UNPAID";
        };
    }

    private Color getStatusColor(PaymentStatus status) {
        if (status == null) {
            return MUTED;
        }

        return switch (status) {
            case PAID -> SUCCESS;
            case PARTIAL -> WARNING;
            case UNPAID -> DANGER;
        };
    }

    private String getMonthName(Integer month) {
        if (month == null) {
            return "-";
        }

        return switch (month) {
            case 1 -> "January";
            case 2 -> "February";
            case 3 -> "March";
            case 4 -> "April";
            case 5 -> "May";
            case 6 -> "June";
            case 7 -> "July";
            case 8 -> "August";
            case 9 -> "September";
            case 10 -> "October";
            case 11 -> "November";
            case 12 -> "December";
            default -> "Month " + month;
        };
    }
}